server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 112.124.34.106:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'

